server:
  port: 8082

spring:
  r2dbc:
    url: r2dbc:postgres://localhost:5432/db_team
    username: postgres
    password: admin
  application:
    name: teen-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/
  instance:
    preferIpAddress: true
    hostName: 192.168.43.77
